version: '3.8'

services:
  database:
    image: postgres:15
    container_name: citi-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=pta
    ports:
      - "5432:5432"